import Head from "next/head";

import axios from "axios";

import Home from "@/components/Home";

function Index({ categoryList, productList }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
      </Head>
      <Home categoryList={categoryList} productList={productList} />
    </>
  );
}
export async function getServerSideProps() {
  const categories = await axios.get(
    `${process.env.NEXT_PUBLIC_API_URL}/categories`
  );
  const products = await axios.get(
    `${process.env.NEXT_PUBLIC_API_URL}/products`
  );

  return {
    props: {
      categoryList: categories.data?.data,
      productList: products.data?.data,
    },
  };
}

export default Index;
